---
# https://github.com/google-github-actions/release-please-action#release-types-supported

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*.*.*'

name: 📤 Upload artifacts

jobs:
  upload-artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-22.04']
        node: ['18']

    steps:
      - name: 📦 Check out the codebase
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: ⚙️ Setup node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org/'

      - name: 📥 Monorepo install
        uses: ./.github/actions/pnpm-install

      - name: ♻️ Restore packages cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.cache
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo
          key: ${{ runner.os }}-packages-cache-${{ hashFiles('**/pnpm*.yaml') }}
          restore-keys: |
            ${{ runner.os }}-packages-cache-${{ hashFiles('**/pnpm*.yaml') }}

      - name: 🚀 Generate dist files
        run: pnpm build:jar

      - name: 📤 Upload release assets
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./out/keywind.jar"]'
